<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ymkDTp.' shared service.

return $this->privates['.service_locator.ymkDTp.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repLog' => ['privates', '.errored..service_locator.ymkDTp..App\\Entity\\RepLog', NULL, 'Cannot autowire service ".service_locator.ymkDTp.": it references class "App\\Entity\\RepLog" but no such service exists.'],
]);
