<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4gURa8H' shared service.

return $this->privates['.service_locator.4gURa8H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'replogRepo' => ['privates', 'App\\Repository\\RepLogRepository', 'getRepLogRepositoryService.php', true],
    'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
