<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ymkDTp..App\Entity\RepLog' shared service.

include_once $this->targetDirs[3].'/src/Entity/RepLog.php';

return $this->privates['.errored..service_locator.ymkDTp..App\\Entity\\RepLog'] = new \App\Entity\RepLog();
