<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDElsCtG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDElsCtG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDElsCtG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDElsCtG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDElsCtG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DElsCtG',
    'container.build_id' => '076cde64',
    'container.build_time' => 1558613593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDElsCtG');
